@base_url = http://localhost:3001
# @base_url = http://3.95.245.34:3001
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiYWxkIiwiZW1haWwiOiJhQGdtYWlsLmNvbSIsImlhdCI6MTczMjMyMTcyMX0.R6jxzqOdYnnwVKD3Wo8aqSgMildKrbPjRrGbjmJCahI

### test api ###
GET {{base_url}}

### register user ###
POST {{base_url}}/auth/register
Content-Type: application/json

{
    "email": "a@gmail.com",
    "username": "ald",
    "password": "123"
}

### login user ###
POST {{base_url}}/auth/login
Content-Type: application/json

{
    "email": "a@gmail.com",
    "password": "123"
}

### get user ###
GET {{base_url}}/user
Content-Type: application/json
x-auth-user:  {{token}}

### update user ###
PUT {{base_url}}/user
Content-Type: application/json
x-auth-user:  {{token}}

{
    "email": "a@gmail.com",
    "username": "al",
    "password": "12",
    "oldPassword": "123"

}

### logout user ###
DELETE {{base_url}}/user
Content-Type: application/json
x-auth-user:  {{token}}


