@base_url = http://localhost:3001
# @base_url = http://3.95.245.34:3001
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiYWxkYSIsImVtYWlsIjoiYUBnbWFpbC5jb20iLCJpYXQiOjE3MzIzMTUzODJ9.jYAWu0Z6yq8bcz5hG7CVSwKcGWMre__sDb1LElYl5OE

GET {{base_url}}

###

POST {{base_url}}/auth/register
Content-Type: application/json

{
    "email": "a@gmail.com",
    "username": "ald",
    "password": "123"
}

###

POST {{base_url}}/auth/login
Content-Type: application/json

{
    "email": "fasdf@gmail.com",
    "password": "123"
}

###

PUT {{base_url}}/user
Content-Type: application/json
x-auth-user:  {{token}}

{
    "email": "a@gmail.com",
    "username": "al",
    "password": "12",
    "oldPassword": "123"

}

###

PUT {{base_url}}/user
Content-Type: application/json
x-auth-user:  {{token}}

{
    "email": "b@gmail.com",
    "username": "al",
    "oldPassword": "12"

}

###


DELETE {{base_url}}/user
Content-Type: application/json
x-auth-user:  {{token}}


